// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3euTUFfVnCrsTVhTpQa0XjIareaU3r8',
    appId: '1:377342984195:web:2fa5fe8d0152a5f6604e36',
    messagingSenderId: '377342984195',
    projectId: 'loan-app1123',
    authDomain: 'loan-app1123.firebaseapp.com',
    storageBucket: 'loan-app1123.firebasestorage.app',
    measurementId: 'G-7WSXBDWKC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBREyr6n7A22XfPlXIBqwidt97t64Qjpls',
    appId: '1:377342984195:android:d7113184353ba9aa604e36',
    messagingSenderId: '377342984195',
    projectId: 'loan-app1123',
    storageBucket: 'loan-app1123.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvCXBkd5rQ4uxABvRsGVczI2fcO-JjGdg',
    appId: '1:377342984195:ios:334d30c81ee7df23604e36',
    messagingSenderId: '377342984195',
    projectId: 'loan-app1123',
    storageBucket: 'loan-app1123.firebasestorage.app',
    iosBundleId: 'com.example.loanApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvCXBkd5rQ4uxABvRsGVczI2fcO-JjGdg',
    appId: '1:377342984195:ios:334d30c81ee7df23604e36',
    messagingSenderId: '377342984195',
    projectId: 'loan-app1123',
    storageBucket: 'loan-app1123.firebasestorage.app',
    iosBundleId: 'com.example.loanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg3euTUFfVnCrsTVhTpQa0XjIareaU3r8',
    appId: '1:377342984195:web:d570ec659cea2988604e36',
    messagingSenderId: '377342984195',
    projectId: 'loan-app1123',
    authDomain: 'loan-app1123.firebaseapp.com',
    storageBucket: 'loan-app1123.firebasestorage.app',
    measurementId: 'G-10GP49L23L',
  );
}
