// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPaif4jyDTxPLT4zjEU1KuKuimSwMH70Y',
    appId: '1:314856867568:web:0f2df80ea93131b8922435',
    messagingSenderId: '314856867568',
    projectId: 'loan-app-3d70e',
    authDomain: 'loan-app-3d70e.firebaseapp.com',
    storageBucket: 'loan-app-3d70e.firebasestorage.app',
    measurementId: 'G-9HTQW8E4YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNmWoCr5vy3JSQs7R7boFbiZ3oI88N6BU',
    appId: '1:314856867568:android:9e11dc377b3375de922435',
    messagingSenderId: '314856867568',
    projectId: 'loan-app-3d70e',
    storageBucket: 'loan-app-3d70e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQvWBgQ8OrXiASIrT4Buzj_2JKXZUcCp0',
    appId: '1:314856867568:ios:fa998a89474b1d22922435',
    messagingSenderId: '314856867568',
    projectId: 'loan-app-3d70e',
    storageBucket: 'loan-app-3d70e.firebasestorage.app',
    iosBundleId: 'com.example.loanApp',
  );
}
